import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import "./App.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Parcoil",
    template: " %s Parcoil",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <Script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js" />
      <Script src="./particles.js" />
      <body>{children}</body>
    </html>
  );
}
